name: MacOS Build x64
run-name: ${{ github.actor }} / ${{ github.event_name }} / ${{ github.sha }}

on: workflow_dispatch

permissions: read-all

jobs:
  build:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - name: Install hatari libs and tools
        run: |
          brew update -q
          brew install -q sdl2 libpng portmidi portaudio readline

      - name: Setup build
        run: |
          mkdir -p build
          cd build
          cmake ../

      - name: Build
        run: |
          cd build
          make

      - name: Post-build
        run: |
          cd build
          chmod +x src/hatari.app/Contents/MacOS/hatari
          cd ../
          mkdir -p output
          mv build/src/hatari.app output/hatari.app

      - uses: actions/upload-artifact@v3
        with:
          name: hatari-macos-x64-${{ github.sha }}
          path: output
