name: Collect MacOS software and create dmg
run-name: ${{ github.actor }} / ${{ github.event_name }} / ${{ github.sha }}

on: workflow_dispatch

permissions: read-all

jobs:
  build:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - name: Create directories
        run: |
          mkdir -p input
          mkdir -p work
          mkdir -p output

      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: macos-fix-libs.yml
          workflow_conclusion: success
          name: hatari-macos-x64-fixed
          path: input/

      - name: Untar files to work directory
        run: |
          cd work
          tar -xvf ../input/hatari.app.tar

      - name: Show xattrs
        run: |
          cd work
          xattr -l hatari.app

      - name: Install tools
        run: |
          brew update -q
          brew install -q create-dmg

      - name: Create dmg
        run: |
          cp work/hatari.app/Contents/Resources/Hatari.icns ./
          create-dmg \
            --volname "Hatari HRDB Development Build" \
            --volicon "Hatari.icns" \
            --icon "hatari.app" 100 120 \
            --hide-extension "hatari.app" \
            --app-drop-link 300 120 \
            --icon-size 100 \
            output/Hatari-HRDB-Development.dmg \
            work/

      - name: Show dmg info (debug)
        run: |
          hdiutil imageinfo output/Hatari-HRDB-Development.dmg

      - name: Setup keychain
        uses: mskelton/macos-certs@v1
        env:
          CERT_P12: ${{ secrets.CERT_P12 }}
          CERT_PASSWORD: ${{ secrets.CERT_PASSWORD }}

      - name: Sign dmg
        run: |
          codesign -s "atari.ephidrena.net" --force output/Hatari-HRDB-Development.dmg --verbose

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: hatari-hrdb-development-${{ github.sha }}.dmg
          path: output/Hatari-HRDB-Development.dmg
