name: Build hrdb for MacOS-x64
run-name: ${{ github.actor }} / ${{ github.event_name }} / ${{ github.sha }}

on: workflow_dispatch

permissions: read-all

jobs:
  build:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - name: Create output directory
        run: |
          mkdir -p output

      - name: Install qt5
        run: |
          brew install qt5
          brew link qt5 --force

      - name: Build hrdb
        run: |
          cd tools/hrdb
          qmake .
          make

      - name: Package hrdb
        run: |
          cd tools/hrdb
          macdeployqt hrdb.app
          find ./
          mv hrdb.app ../../output/

      - name: Tar hrdb
        run: |
          cd output
          tar -cvf hrdb-macos-x64.tar hrdb.app ../tools/hrdb/docs/hrdb_release_notes.txt

      - uses: actions/upload-artifact@v3
        with:
          name: hrdb-macos-x64
          path: output/hrdb-macos-x64.tar
