name: MacOS Build
run-name: ${{ github.actor }} / ${{ github.event_name }} / ${{ github.sha }}

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch

permissions: read-all

jobs:
  build:
    runs-on: macos-12

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v3

        # Runs a set of commands using the runners shell
        - name: Install hatari libs and tools
          run: |
            brew install cmake sdl2 libpng portmidi portaudio readline
        - name: Build hatari
          run: |
            mkdir -p build
            cd build
            cmake ../
            make
            mv ./src/hatari.app output/

        - name: Fix libraries
          run: |
            OTOOL=/usr/bin/otool
            CONTENTDIR=output/hatari.app/Contents
            EXECUTABLE=CONTENTDIR/MacOS/hatari
            TARGETDIR=$CONTENTDIR/Frameworks
            LIBDIR="@executable_path/../Frameworks"
            SOURCEDIR=`brew --prefix`/lib

            mkdir -p ${TARGETDIR}

            echo "Looking for libs that need fixing in executable $EXECUTABLE"
            ${OTOOL} -l ${EXECUTABLE} \
              | awk '/dylib/&&!/\usr\/lib/{print $2}' \
              | sed 's:.*/::' \
              > /tmp/libs.txt

            echo "Detected libs that needs fixing:"
            cat /tmp/libs.txt
            echo "---"

            while read lib; do
              echo "copying $SOURCEDIR/$lib -> $TARGETDIR/$lib"
              cp ${SOURCEDIR}/$lib ${TARGETDIR}

              TARGET="$TARGETDIR/$lib"
              NEW_FILE=`basename ${TARGET}`
              ORIGINAL_ID=`${OTOOL} -DX ${TARGET}`
              NEW_ID=${LIBDIR}/${NEW_FILE}

              echo "changing id for $TARGET with id $ORIGINAL_ID to $NEW_ID"
              install_name_tool -id ${NEW_ID} ${TARGET}
              install_name_tool -change ${ORIGINAL_ID} ${NEW_ID} ${EXECUTABLE}
              #echo "signing libs using self signed certificate (for now)"
              #codesign -s "atari.ephidrena.net" --force $TARGET
            done < /tmp/libs.txt

        #        run: |
        #          brew install qt5
        #          cd tools/hrdb
        #          qmake .
        #          make
        #          chmod +x hrdb.app/Contents/MacOS/hrdb
        #      - name: Package hrdb
        #        run: |
        #           cd tools/hrdb
        #           macdeployqt hrdb.app
        #           ls -Rl *
        #           mv hrdb.app ../../output/
        #
        - name: zip outputs
          run: |
            cd output
            #cp ../tools/hrdb/docs/hrdb_release_notes.txt .
            cp ../gpl.txt .
            #zip -r macos-hrdb.zip hrdb.app hatari.app *.txt
            zip -r test0-hatari.zip hatari.app *.txt
        - name: Upload artifacts
          uses: actions/upload-artifact@v2
          with:
            name: hrdb-${{ github.sha }}
            path: output/test0-hatari.zip
