name: Build hrdb for MacOS-x64
run-name: ${{ github.actor }} / ${{ github.event_name }} / ${{ github.sha }}

on: workflow_dispatch

permissions: read-all

jobs:
  build:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - name: Create output directory
        run: |
          mkdir -p output

      - name: Install qt5
        run: |
          brew install qt5 libpng
          brew link qt5 --force
          brew link libpng --force

      - name: Build hrdb
        run: |
          export BREW_PREFIX_QT5=$(brew --prefix qt5)
          export PATH="$BREW_PREFIX_QT5/bin:$PATH"
          export LDFLAGS="-L$BREW_PREFIX_QT5/lib"
          export CPPFLAGS="-I$BREW_PREFIX_QT5/include"
          export PKG_CONFIG_PATH="$BREW_PREFIX_QT5/lib/pkgconfig"

          cd tools/hrdb
          qmake .
          make

      - name: Package hrdb
        run: |
          cd tools/hrdb
          macdeployqt hrdb.app -verbose=2 -no-plugins

      - name: Tar hrdb
        run: |
          cd tools/hrdb
          find hrdb.app -name "*.dylib" -exec chmod +x {} \;
          tar -cvf ../../output/hrdb-macos-x64.tar hrdb.app
          cd docs
          tar -rf  ../../../output/hrdb-macos-x64.tar hrdb_release_notes.txt

      - uses: actions/upload-artifact@v3
        with:
          name: hrdb-macos-x64
          path: output/hrdb-macos-x64.tar
